import React from 'react'
// import 

const Text = () => {
  return (
    <div>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis modi voluptates corporis dignissimos aliquam atque at perferendis in deleniti cupiditate, excepturi aperiam incidunt rerum voluptas nesciunt rem recusandae quo quia cum molestias totam. Vero cupiditate beatae amet fuga. Voluptas, distinctio perspiciatis! Dicta alias provident nostrum quod, reprehenderit incidunt, eum sapiente quidem quos assumenda doloribus minima numquam quam magnam consequatur saepe tempora. Explicabo sunt enim veritatis eum ullam impedit facere tempore soluta quis quaerat deleniti, placeat adipisci ea quibusdam fuga, voluptas expedita harum officiis velit. Possimus sequi tenetur enim dicta, illo natus incidunt architecto cum distinctio, laboriosam at magni iste nisi culpa excepturi error iure. Dolores quas illum nobis repudiandae exercitationem porro dolorum consequatur veritatis, atque praesentium magnam commodi non nisi. Tempora rem, nesciunt perferendis dolorem eveniet ut nihil molestias in. Cum sapiente rem ab. Debitis animi natus accusantium dolores? Consequuntur pariatur non, maxime consequatur voluptates reiciendis totam vero voluptatum voluptatem sapiente cumque quia eaque provident. Officia ipsum qui earum sed. Facilis eligendi voluptatem voluptates dolores obcaecati, eius aliquam reprehenderit cum! Eligendi dolore ea quaerat eum impedit corporis quia aut, hic non incidunt ab consequatur laboriosam dignissimos alias magni distinctio vel. Quia quod fugiat distinctio totam, voluptatibus nisi perspiciatis voluptates explicabo deleniti dolor cumque velit nesciunt, ipsam dicta iusto nam?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis modi voluptates corporis dignissimos aliquam atque at perferendis in deleniti cupiditate, excepturi aperiam incidunt rerum voluptas nesciunt rem recusandae quo quia cum molestias totam. Vero cupiditate beatae amet fuga. Voluptas, distinctio perspiciatis! Dicta alias provident nostrum quod, reprehenderit incidunt, eum sapiente quidem quos assumenda doloribus minima numquam quam magnam consequatur saepe tempora. Explicabo sunt enim veritatis eum ullam impedit facere tempore soluta quis quaerat deleniti, placeat adipisci ea quibusdam fuga, voluptas expedita harum officiis velit. Possimus sequi tenetur enim dicta, illo natus incidunt architecto cum distinctio, laboriosam at magni iste nisi culpa excepturi error iure. Dolores quas illum nobis repudiandae exercitationem porro dolorum consequatur veritatis, atque praesentium magnam commodi non nisi. Tempora rem, nesciunt perferendis dolorem eveniet ut nihil molestias in. Cum sapiente rem ab. Debitis animi natus accusantium dolores? Consequuntur pariatur non, maxime consequatur voluptates reiciendis totam vero voluptatum voluptatem sapiente cumque quia eaque provident. Officia ipsum qui earum sed. Facilis eligendi voluptatem voluptates dolores obcaecati, eius aliquam reprehenderit cum! Eligendi dolore ea quaerat eum impedit corporis quia aut, hic non incidunt ab consequatur laboriosam dignissimos alias magni distinctio vel. Quia quod fugiat distinctio totam, voluptatibus nisi perspiciatis voluptates explicabo deleniti dolor cumque velit nesciunt, ipsam dicta iusto nam?</p>
        
    </div>
  )
}

export default Text